# estudo dos dados do Banco Central

este Colab tem como objetivo baixar, tratar e analisar os dados do Banco Central
utilizados no projeto de API do 3º semestre para a empresa DM.

a análise busca identificar informações relevantes sobre operações de crédito,
carteira ativa, inadimplência e ativos problemáticos, com o propósito de auxiliar
na identificação de regiões com maior potencial de expansão sustentável de crédito.

os resultados gerados aqui servem de base para os indicadores e gráficos exibidos
no dashboard do projeto.

> **observação:** este notebook foi utilizado principalmente como ambiente de
> estudo e exploração dos dados ao longo do desenvolvimento. por isso, além das
> análises finais, ele também contém células de exploração, testes e versões
> anteriores de cálculos — mantidas propositalmente como registro do processo
> de evolução da metodologia, e organizadas na seção de anexo ao final.

### como navegar neste notebook

o notebook está dividido em seções, cada uma correspondente a uma etapa da análise
ou a uma página do dashboard:

1. **ingestão e preparação dos dados** — download e tratamento dos dados brutos do BCB
2. **utilitários** — funções e estruturas auxiliares reutilizadas ao longo do notebook
3. **visão geral nacional** — indicadores nacionais exibidos na página inicial do dashboard
4. **mercado por estado** — análise comparativa entre estados (página "mercado")
5. **risco de crédito** — indicadores e mapas de inadimplência (página "risco")
6. **score de expansão sustentável** — cálculo do índice de potencial de expansão por estado (página "expansão")
7. **anexo — exploração e versões anteriores** — análises exploratórias e versões
   anteriores da metodologia, mantidas como histórico do desenvolvimento

## ingestão e preparação dos dados

In [1]:
# código responsável por baixar o arquivo ZIP do SCR do Banco Central.
# ele baixa automaticamente os dados do ano anterior.

import datetime
import requests

def baixar_zip():
    ano_anterior = datetime.datetime.now().year - 1
    url = f"https://www.bcb.gov.br/pda/desig/scrdata_{ano_anterior}.zip"
    filename = f"scrdata_{ano_anterior}.zip"

    with requests.get(url, stream=True) as r:
        r.raise_for_status()

        with open(filename, "wb") as f:
            for chunk in r.iter_content(chunk_size=8192):
                f.write(chunk)

    return filename

filename = baixar_zip()

In [2]:
# lê todos os CSVs dentro do zip do BCB, filtrando apenas as colunas necessárias.
# converte data_base para datetime e as colunas numéricas de string com vírgula para float.
# concatena todos os meses em um único DataFrame e libera a lista intermediária da memória.

import pandas as pd
import zipfile

colunas = [
    "data_base", "uf", "numero_de_operacoes",
    "carteira_ativa", "carteira_inadimplencia",
    "ativo_problematico", "porte", "cliente",
]

colunas_numericas = [
    "carteira_ativa",
    "carteira_inadimplencia",
    "ativo_problematico",
]

dfs = []

with zipfile.ZipFile(filename) as zf:
    for nome in zf.namelist():
        with zf.open(nome) as file:
            df = pd.read_csv(file, sep=";", usecols=colunas)
            df["numero_de_operacoes"] = df["numero_de_operacoes"].replace(-1, pd.NA)

            df = df.assign(
                data_base=pd.to_datetime(df["data_base"]),
                **{
                    col: pd.to_numeric(
                        df[col].astype(str).str.replace(",", ".", regex=False),
                        errors="coerce",
                    )
                    for col in colunas_numericas
                }
            )

            df = df[df["porte"] != "Indisponível"]

            # vai agrupar pelo by= e depois somar os valores numéricos, o as_index=false faz com que os valores do by= não se tornem indices
            df_agrupado = df.groupby(
                by=["data_base", "uf", "porte", "cliente"],
                as_index=False
            )[["numero_de_operacoes", "carteira_ativa", "carteira_inadimplencia", "ativo_problematico"]].sum()
            dfs.append(df_agrupado)

dt = pd.concat(dfs, ignore_index=True)
del dfs

### colunas utilizadas no tratamento dos dados

após o filtro, usamos apenas as colunas necessárias para a análise:

- `data_base`: data de referência dos dados. O mais importante aqui é o mês e o ano.
- `uf`: sigla do estado.
- `numero_de_operacoes`: quantidade de operações registradas.
- `carteira_ativa`: valor da carteira ativa.
- `carteira_inadimplencia`: valor da carteira inadimplente.
- `ativo_problematico`: valor dos ativos problemáticos.
- `porte`: porte do cliente.
- `cliente`: tipo de cliente, PF ou PJ.

### tipos de porte

#### pessoa Física (PF)

- Até 1 salário mínimo
- Mais de 1 a 2 salários mínimos
- Mais de 2 a 3 salários mínimos
- Mais de 3 a 5 salários mínimos
- Mais de 5 a 10 salários mínimos
- Mais de 10 a 20 salários mínimos
- Acima de 20 salários mínimos
- Sem rendimento

#### pessoa Jurídica (PJ)

- Micro
- Pequeno
- Médio
- Grande

## utilitários

In [3]:
# função auxiliar para formatar valores financeiros grandes.
# exemplo: 2.000.000.000 vira R$ 2,00B.

def formatar_dinheiro(valor):
    valor = float(valor)

    if abs(valor) >= 1_000_000_000_000:
        resultado = f"R$ {valor / 1_000_000_000_000:.2f}T"
    elif abs(valor) >= 1_000_000_000:
        resultado = f"R$ {valor / 1_000_000_000:.2f}B"
    elif abs(valor) >= 1_000_000:
        resultado = f"R$ {valor / 1_000_000:.2f}M"
    elif abs(valor) >= 1_000:
        resultado = f"R$ {valor / 1_000:.2f}K"
    else:
        resultado = f"R$ {valor:.2f}"

    return resultado.replace(".", ",")

In [4]:
# nomes completos dos estados, usados para exibir os dados de forma
# mais legivel nas tabelas e no mapa do dashboard.

nomes_estados = {
    "AC": "Acre",
    "AL": "Alagoas",
    "AP": "Amapá",
    "AM": "Amazonas",
    "BA": "Bahia",
    "CE": "Ceará",
    "DF": "Distrito Federal",
    "ES": "Espírito Santo",
    "GO": "Goiás",
    "MA": "Maranhão",
    "MT": "Mato Grosso",
    "MS": "Mato Grosso do Sul",
    "MG": "Minas Gerais",
    "PA": "Pará",
    "PB": "Paraíba",
    "PR": "Paraná",
    "PE": "Pernambuco",
    "PI": "Piauí",
    "RJ": "Rio de Janeiro",
    "RN": "Rio Grande do Norte",
    "RS": "Rio Grande do Sul",
    "RO": "Rondônia",
    "RR": "Roraima",
    "SC": "Santa Catarina",
    "SP": "São Paulo",
    "SE": "Sergipe",
    "TO": "Tocantins",
}

In [5]:
# mapeamento de cada UF para sua regiao geografica, usado para agrupar
# e comparar dados em nivel regional (mercado e risco).

regioes = {
    "SP": "Sudeste",
    "RJ": "Sudeste",
    "MG": "Sudeste",
    "ES": "Sudeste",

    "PR": "Sul",
    "SC": "Sul",
    "RS": "Sul",

    "DF": "Centro-Oeste",
    "GO": "Centro-Oeste",
    "MT": "Centro-Oeste",
    "MS": "Centro-Oeste",

    "BA": "Nordeste",
    "SE": "Nordeste",
    "AL": "Nordeste",
    "PE": "Nordeste",
    "PB": "Nordeste",
    "RN": "Nordeste",
    "PI": "Nordeste",
    "CE": "Nordeste",
    "MA": "Nordeste",

    "AM": "Norte",
    "RR": "Norte",
    "AP": "Norte",
    "PA": "Norte",
    "TO": "Norte",
    "AC": "Norte",
    "RO": "Norte",
}

## visão geral nacional

In [6]:
# soma total da carteira ativa no ano inteiro.

carteira_ativa_total = dt["carteira_ativa"].sum()

print(f"Carteira ativa total: {formatar_dinheiro(carteira_ativa_total)}")

Carteira ativa total: R$ 81,56T

In [7]:
# crescimento da carteira ativa.
# compara a data mais antiga com a data mais recente do período.

data_inicial = dt["data_base"].min()
data_final = dt["data_base"].max()

carteira_inicial = dt[dt["data_base"] == data_inicial]["carteira_ativa"].sum()
carteira_final = dt[dt["data_base"] == data_final]["carteira_ativa"].sum()

crescimento_carteira_ativa = (
    (carteira_final - carteira_inicial) * 100
    / carteira_inicial
)

print(f"Crescimento da carteira ativa: {crescimento_carteira_ativa:.2f}%")

Crescimento da carteira ativa: 11.57%

In [8]:
# taxa de inadimplência ponderada pela carteira ativa.
# fórmula: carteira inadimplente total * 100 / carteira ativa total

carteira_inadimplencia_total = dt["carteira_inadimplencia"].sum()

taxa_inadimplencia = (
    carteira_inadimplencia_total * 100
    / carteira_ativa_total
)

print(f"Taxa de inadimplência: {taxa_inadimplencia:.2f}%")

Taxa de inadimplência: 3.81%

In [9]:
# soma total do número de operações no período analisado.

total_operacoes = dt["numero_de_operacoes"].sum()

print(f"Total de operações: {formatar_dinheiro(total_operacoes)}")

Total de operações: R$ 9,82B

In [10]:
# estado em destaque.
# soma a carteira ativa por estado e data.
# depois pega o valor mais recente de cada estado.

carteira_por_estado_data = (
    dt.groupby(["uf", "data_base"], as_index=False)["carteira_ativa"]
    .sum()
)

data_mais_recente_por_estado = (
    carteira_por_estado_data
    .sort_values("data_base")
    .groupby("uf", as_index=False)
    .tail(1)
)

estado_destaque = (
    data_mais_recente_por_estado
    .sort_values("carteira_ativa", ascending=False)
    .iloc[0]
)

print(f"Estado em destaque: {estado_destaque['uf']}")

Estado em destaque: SP

In [11]:
# maior crescimento da carteira ativa.
# compara a carteira ativa mais antiga e mais recente de cada estado.

carteira_ordenada = carteira_por_estado_data.sort_values(["uf", "data_base"])

carteira_inicial_estado = (
    carteira_ordenada
    .groupby("uf", as_index=False)
    .first()
    .rename(columns={
        "data_base": "data_inicial",
        "carteira_ativa": "carteira_inicial"
    })
)

carteira_final_estado = (
    carteira_ordenada
    .groupby("uf", as_index=False)
    .last()
    .rename(columns={
        "data_base": "data_final",
        "carteira_ativa": "carteira_final"
    })
)

crescimento_por_estado = carteira_inicial_estado.merge(
    carteira_final_estado,
    on="uf"
)

crescimento_por_estado["taxa_crescimento"] = (
    (crescimento_por_estado["carteira_final"] - crescimento_por_estado["carteira_inicial"])
    * 100
    / crescimento_por_estado["carteira_inicial"]
)

maior_crescimento = (
    crescimento_por_estado
    .sort_values("taxa_crescimento", ascending=False)
    .iloc[0]
)

print(f"Estado com maior crescimento: {maior_crescimento['uf']}")
print(f"Crescimento: {maior_crescimento['taxa_crescimento']:.2f}%")

Estado com maior crescimento: TO
Crescimento: 17.99%

In [12]:
# simula os dados usados no mapa interativo.
# mostra por estado: nome, carteira ativa atual, taxa de crescimento e classificacao do mapa.
# usa o dicionario nomes_estados definido na secao de utilitarios.

carteira_por_estado_data = (
    dt.groupby(["uf", "data_base"], as_index=False)["carteira_ativa"]
    .sum()
)

carteira_ordenada = carteira_por_estado_data.sort_values(["uf", "data_base"])

carteira_inicial_estado = (
    carteira_ordenada
    .groupby("uf", as_index=False)
    .first()
    .rename(columns={
        "data_base": "data_inicial",
        "carteira_ativa": "carteira_inicial"
    })
)

carteira_final_estado = (
    carteira_ordenada
    .groupby("uf", as_index=False)
    .last()
    .rename(columns={
        "data_base": "data_final",
        "carteira_ativa": "carteira_ativa"
    })
)

dados_mapa = carteira_final_estado.merge(
    carteira_inicial_estado,
    on="uf"
)

dados_mapa["taxa_crescimento"] = (
    (dados_mapa["carteira_ativa"] - dados_mapa["carteira_inicial"])
    * 100
    / dados_mapa["carteira_inicial"]
)

dados_mapa["nome_estado"] = dados_mapa["uf"].map(nomes_estados)

max_carteira = dados_mapa["carteira_ativa"].max()
threshold = max_carteira * 0.5

dados_mapa["classificacao_mapa"] = dados_mapa["carteira_ativa"].apply(
    lambda valor: "Alta atividade" if valor >= threshold else "Alto crescimento"
)

tabela_mapa = dados_mapa[[
    "uf",
    "nome_estado",
    "carteira_ativa",
    "taxa_crescimento",
    "classificacao_mapa",
    "data_inicial",
    "data_final",
]].copy()

tabela_mapa = tabela_mapa.sort_values("carteira_ativa", ascending=False)

tabela_mapa["carteira_ativa"] = tabela_mapa["carteira_ativa"].apply(formatar_dinheiro)
tabela_mapa["taxa_crescimento"] = tabela_mapa["taxa_crescimento"].map(lambda x: f"{x:.2f}%")

display(tabela_mapa)

print(f"Maior carteira ativa: {formatar_dinheiro(max_carteira)}")
print(f"Limite de 50%: {formatar_dinheiro(threshold)}")

,uf,nome_estado,carteira_ativa,taxa_crescimento,classificacao_mapa,data_inicial,data_final
25,SP,São Paulo,"R$ 2,19T",17.38%,Alta atividade,2025-01-31,2025-12-31
10,MG,Minas Gerais,"R$ 632,54B",8.17%,Alto crescimento,2025-01-31,2025-12-31
17,PR,Paraná,"R$ 537,32B",9.36%,Alto crescimento,2025-01-31,2025-12-31
18,RJ,Rio de Janeiro,"R$ 534,09B",4.01%,Alto crescimento,2025-01-31,2025-12-31
22,RS,Rio Grande do Sul,"R$ 516,60B",11.50%,Alto crescimento,2025-01-31,2025-12-31
23,SC,Santa Catarina,"R$ 391,96B",9.71%,Alto crescimento,2025-01-31,2025-12-31
8,GO,Goiás,"R$ 330,17B",9.33%,Alto crescimento,2025-01-31,2025-12-31
4,BA,Bahia,"R$ 271,84B",9.36%,Alto crescimento,2025-01-31,2025-12-31
12,MT,Mato Grosso,"R$ 255,81B",6.61%,Alto crescimento,2025-01-31,2025-12-31
6,DF,Distrito Federal,"R$ 169,42B",5.93%,Alto crescimento,2025-01-31,2025-12-31
15,PE,Pernambuco,"R$ 163,11B",11.54%,Alto crescimento,2025-01-31,2025-12-31
5,CE,Ceará,"R$ 161,50B",13.34%,Alto crescimento,2025-01-31,2025-12-31
13,PA,Pará,"R$ 156,07B",12.07%,Alto crescimento,2025-01-31,2025-12-31
11,MS,Mato Grosso do Sul,"R$ 136,85B",6.70%,Alto crescimento,2025-01-31,2025-12-31
7,ES,Espírito Santo,"R$ 123,53B",12.50%,Alto crescimento,2025-01-31,2025-12-31
9,MA,Maranhão,"R$ 108,51B",11.56%,Alto crescimento,2025-01-31,2025-12-31
2,AM,Amazonas,"R$ 76,03B",17.05%,Alto crescimento,2025-01-31,2025-12-31
14,PB,Paraíba,"R$ 72,23B",11.95%,Alto crescimento,2025-01-31,2025-12-31
19,RN,Rio Grande do Norte,"R$ 67,27B",10.02%,Alto crescimento,2025-01-31,2025-12-31
16,PI,Piauí,"R$ 63,33B",10.73%,Alto crescimento,2025-01-31,2025-12-31
20,RO,Rondônia,"R$ 62,20B",6.83%,Alto crescimento,2025-01-31,2025-12-31
1,AL,Alagoas,"R$ 56,47B",11.33%,Alto crescimento,2025-01-31,2025-12-31
26,TO,Tocantins,"R$ 55,94B",17.99%,Alto crescimento,2025-01-31,2025-12-31
24,SE,Sergipe,"R$ 43,70B",11.69%,Alto crescimento,2025-01-31,2025-12-31
0,AC,Acre,"R$ 18,70B",9.54%,Alto crescimento,2025-01-31,2025-12-31
3,AP,Amapá,"R$ 18,34B",15.55%,Alto crescimento,2025-01-31,2025-12-31
21,RR,Roraima,"R$ 15,39B",17.60%,Alto crescimento,2025-01-31,2025-12-31

Maior carteira ativa: R$ 2,19T
Limite de 50%: R$ 1,10T

## mercado por estado

In [13]:
# ranking dos estados por carteira ativa atual.
# usa a carteira ativa mais recente de cada estado e calcula o crescimento desde a primeira data disponível.

carteira_por_estado_data = (
    dt.groupby(["uf", "data_base"], as_index=False)["carteira_ativa"]
    .sum()
)

carteira_ordenada = carteira_por_estado_data.sort_values(["uf", "data_base"])

carteira_inicial_estado = (
    carteira_ordenada
    .groupby("uf", as_index=False)
    .first()
    .rename(columns={
        "data_base": "data_inicial",
        "carteira_ativa": "valor_anterior"
    })
)

carteira_final_estado = (
    carteira_ordenada
    .groupby("uf", as_index=False)
    .last()
    .rename(columns={
        "data_base": "data_final",
        "carteira_ativa": "carteira_ativa"
    })
)

ranking_estados = carteira_final_estado.merge(
    carteira_inicial_estado,
    on="uf"
)

ranking_estados["taxa_crescimento"] = (
    (ranking_estados["carteira_ativa"] - ranking_estados["valor_anterior"])
    * 100
    / ranking_estados["valor_anterior"]
)

ranking_estados = ranking_estados.sort_values(
    "carteira_ativa",
    ascending=False
).reset_index(drop=True)

ranking_estados["posicao"] = ranking_estados.index + 1

tabela_ranking_estados = ranking_estados[[
    "posicao",
    "uf",
    "carteira_ativa",
    "taxa_crescimento",
    "valor_anterior",
    "data_inicial",
    "data_final",
]].copy()

tabela_ranking_estados["carteira_ativa"] = tabela_ranking_estados["carteira_ativa"].apply(formatar_dinheiro)
tabela_ranking_estados["valor_anterior"] = tabela_ranking_estados["valor_anterior"].apply(formatar_dinheiro)
tabela_ranking_estados["taxa_crescimento"] = tabela_ranking_estados["taxa_crescimento"].map(lambda x: f"{x:.2f}%")

display(tabela_ranking_estados)

,posicao,uf,carteira_ativa,taxa_crescimento,valor_anterior,data_inicial,data_final
0,1,SP,"R$ 2,19T",17.38%,"R$ 1,87T",2025-01-31,2025-12-31
1,2,MG,"R$ 632,54B",8.17%,"R$ 584,76B",2025-01-31,2025-12-31
2,3,PR,"R$ 537,32B",9.36%,"R$ 491,32B",2025-01-31,2025-12-31
3,4,RJ,"R$ 534,09B",4.01%,"R$ 513,50B",2025-01-31,2025-12-31
4,5,RS,"R$ 516,60B",11.50%,"R$ 463,33B",2025-01-31,2025-12-31
5,6,SC,"R$ 391,96B",9.71%,"R$ 357,29B",2025-01-31,2025-12-31
6,7,GO,"R$ 330,17B",9.33%,"R$ 302,00B",2025-01-31,2025-12-31
7,8,BA,"R$ 271,84B",9.36%,"R$ 248,58B",2025-01-31,2025-12-31
8,9,MT,"R$ 255,81B",6.61%,"R$ 239,96B",2025-01-31,2025-12-31
9,10,DF,"R$ 169,42B",5.93%,"R$ 159,94B",2025-01-31,2025-12-31
10,11,PE,"R$ 163,11B",11.54%,"R$ 146,24B",2025-01-31,2025-12-31
11,12,CE,"R$ 161,50B",13.34%,"R$ 142,49B",2025-01-31,2025-12-31
12,13,PA,"R$ 156,07B",12.07%,"R$ 139,26B",2025-01-31,2025-12-31
13,14,MS,"R$ 136,85B",6.70%,"R$ 128,26B",2025-01-31,2025-12-31
14,15,ES,"R$ 123,53B",12.50%,"R$ 109,81B",2025-01-31,2025-12-31
15,16,MA,"R$ 108,51B",11.56%,"R$ 97,27B",2025-01-31,2025-12-31
16,17,AM,"R$ 76,03B",17.05%,"R$ 64,95B",2025-01-31,2025-12-31
17,18,PB,"R$ 72,23B",11.95%,"R$ 64,52B",2025-01-31,2025-12-31
18,19,RN,"R$ 67,27B",10.02%,"R$ 61,14B",2025-01-31,2025-12-31
19,20,PI,"R$ 63,33B",10.73%,"R$ 57,19B",2025-01-31,2025-12-31
20,21,RO,"R$ 62,20B",6.83%,"R$ 58,22B",2025-01-31,2025-12-31
21,22,AL,"R$ 56,47B",11.33%,"R$ 50,72B",2025-01-31,2025-12-31
22,23,TO,"R$ 55,94B",17.99%,"R$ 47,41B",2025-01-31,2025-12-31
23,24,SE,"R$ 43,70B",11.69%,"R$ 39,13B",2025-01-31,2025-12-31
24,25,AC,"R$ 18,70B",9.54%,"R$ 17,07B",2025-01-31,2025-12-31
25,26,AP,"R$ 18,34B",15.55%,"R$ 15,87B",2025-01-31,2025-12-31
26,27,RR,"R$ 15,39B",17.60%,"R$ 13,09B",2025-01-31,2025-12-31

In [14]:
# participação regional na carteira ativa.
# agrupa os estados por região (dicionario regioes definido na secao de
# utilitarios) e calcula quanto cada regiao representa no total.

dt_regioes = dt.copy()
dt_regioes["regiao"] = dt_regioes["uf"].map(regioes)

carteira_por_regiao = (
    dt_regioes
    .groupby("regiao", as_index=False)["carteira_ativa"]
    .sum()
)

carteira_total = carteira_por_regiao["carteira_ativa"].sum()

carteira_por_regiao["participacao_percentual"] = (
    carteira_por_regiao["carteira_ativa"] * 100
    / carteira_total
)

carteira_por_regiao = carteira_por_regiao.sort_values(
    "participacao_percentual",
    ascending=False
)

tabela_participacao_regional = carteira_por_regiao.copy()

tabela_participacao_regional["carteira_ativa"] = tabela_participacao_regional["carteira_ativa"].apply(formatar_dinheiro)
tabela_participacao_regional["participacao_percentual"] = tabela_participacao_regional["participacao_percentual"].map(lambda x: f"{x:.2f}%")

display(tabela_participacao_regional)

         regiao carteira_ativa participacao_percentual
3       Sudeste      R$ 38,97T                  47.78%
4           Sul      R$ 16,44T                  20.16%
1      Nordeste      R$ 11,43T                  14.01%
0  Centro-Oeste      R$ 10,20T                  12.50%
2         Norte       R$ 4,52T                   5.55%

## risco de crédito

In [15]:
# KPIs principais da página de risco.

# inadimplência média geral.
# usa a base inteira, seguindo a lógica da rota /kpis.
inadimplencia_media = (
    dt["carteira_inadimplencia"].sum() * 100
    / dt["carteira_ativa"].sum()
)

# base da última data, usada pelos indicadores regionais.
ultima_data = dt["data_base"].max()
dt_ultima_data = dt[dt["data_base"] == ultima_data].copy()

# usa o dicionario regioes definido na secao de utilitarios.
dt_ultima_data["regiao"] = dt_ultima_data["uf"].map(regioes)

indicadores_regioes = (
    dt_ultima_data
    .groupby("regiao", as_index=False)
    .agg({
        "carteira_ativa": "sum",
        "carteira_inadimplencia": "sum",
        "ativo_problematico": "sum",
    })
)

indicadores_regioes["taxa_inadimplencia"] = (
    indicadores_regioes["carteira_inadimplencia"] * 100
    / indicadores_regioes["carteira_ativa"]
)

indicadores_regioes["taxa_ativo_problematico"] = (
    indicadores_regioes["ativo_problematico"] * 100
    / indicadores_regioes["carteira_ativa"]
)

# o card de ativo problemático usa a média simples das taxas regionais.
ativo_problematico_medio = indicadores_regioes["taxa_ativo_problematico"].mean()

regiao_critica = indicadores_regioes.sort_values(
    "taxa_inadimplencia",
    ascending=False
).iloc[0]

regiao_menos_critica = indicadores_regioes.sort_values(
    "taxa_inadimplencia",
    ascending=True
).iloc[0]

kpis_risco = pd.DataFrame({
    "Indicador": [
        "Inadimplência média",
        "Ativo problemático médio",
        "Região crítica",
        "Região menos crítica",
        "Data usada nos indicadores regionais",
    ],
    "Valor": [
        f"{inadimplencia_media:.2f}%",
        f"{ativo_problematico_medio:.2f}%",
        f"{regiao_critica['regiao']} ({regiao_critica['taxa_inadimplencia']:.2f}%)",
        f"{regiao_menos_critica['regiao']} ({regiao_menos_critica['taxa_inadimplencia']:.2f}%)",
        ultima_data.date(),
    ]
})

display(kpis_risco)

                              Indicador            Valor
0                   Inadimplência média            3.81%
1              Ativo problemático médio            8.00%
2                        Região crítica    Norte (5.57%)
3                  Região menos crítica  Sudeste (3.52%)
4  Data usada nos indicadores regionais       2025-12-31

In [16]:
# indicadores regionais usados no gráfico da página de risco.
# usa somente a última data_base.

tabela_risco_regioes = indicadores_regioes[[
    "regiao",
    "taxa_inadimplencia",
    "taxa_ativo_problematico",
    "carteira_ativa",
    "carteira_inadimplencia",
    "ativo_problematico",
]].copy()

tabela_risco_regioes = tabela_risco_regioes.sort_values(
    "taxa_inadimplencia",
    ascending=False
)

tabela_risco_regioes["taxa_inadimplencia"] = tabela_risco_regioes["taxa_inadimplencia"].map(lambda x: f"{x:.2f}%")
tabela_risco_regioes["taxa_ativo_problematico"] = tabela_risco_regioes["taxa_ativo_problematico"].map(lambda x: f"{x:.2f}%")
tabela_risco_regioes["carteira_ativa"] = tabela_risco_regioes["carteira_ativa"].apply(formatar_dinheiro)
tabela_risco_regioes["carteira_inadimplencia"] = tabela_risco_regioes["carteira_inadimplencia"].apply(formatar_dinheiro)
tabela_risco_regioes["ativo_problematico"] = tabela_risco_regioes["ativo_problematico"].apply(formatar_dinheiro)

display(tabela_risco_regioes)

,regiao,taxa_inadimplencia,taxa_ativo_problematico,carteira_ativa,carteira_inadimplencia,ativo_problematico
2,Norte,5.57%,8.73%,"R$ 402,66B","R$ 22,42B","R$ 35,15B"
1,Nordeste,5.18%,8.37%,"R$ 1,01T","R$ 52,26B","R$ 84,38B"
0,Centro-Oeste,5.18%,9.16%,"R$ 892,26B","R$ 46,23B","R$ 81,72B"
4,Sul,3.72%,6.72%,"R$ 1,45T","R$ 53,80B","R$ 97,18B"
3,Sudeste,3.52%,7.03%,"R$ 3,48T","R$ 122,52B","R$ 244,71B"

In [17]:
# heatmap de inadimplência para Pessoa Física.
# calcula a inadimplência por estado e porte usando a base inteira.

dt_pf = dt[dt["cliente"] == "PF"].copy()

heatmap_pf = (
    dt_pf
    .groupby(["porte", "uf"], as_index=False)
    .agg({
        "carteira_ativa": "sum",
        "carteira_inadimplencia": "sum",
    })
)

heatmap_pf["taxa_inadimplencia"] = (
    heatmap_pf["carteira_inadimplencia"] * 100
    / heatmap_pf["carteira_ativa"]
)

matriz_pf = heatmap_pf.pivot(
    index="porte",
    columns="uf",
    values="taxa_inadimplencia"
)

ordem_porte_pf = [
    "Sem rendimento",
    "Até 1 salário mínimo",
    "Mais de 1 a 2 salários mínimos",
    "Mais de 2 a 3 salários mínimos",
    "Mais de 3 a 5 salários mínimos",
    "Mais de 5 a 10 salários mínimos",
    "Mais de 10 a 20 salários mínimos",
    "Acima de 20 salários mínimos",
]

matriz_pf = matriz_pf.reindex(ordem_porte_pf)

display(matriz_pf.style.format("{:.2f}%"))

In [18]:
# heatmap de inadimplência para Pessoa Jurídica.
# calcula a inadimplência por estado e porte usando a base inteira.

dt_pj = dt[dt["cliente"] == "PJ"].copy()

heatmap_pj = (
    dt_pj
    .groupby(["porte", "uf"], as_index=False)
    .agg({
        "carteira_ativa": "sum",
        "carteira_inadimplencia": "sum",
    })
)

heatmap_pj["taxa_inadimplencia"] = (
    heatmap_pj["carteira_inadimplencia"] * 100
    / heatmap_pj["carteira_ativa"]
)

matriz_pj = heatmap_pj.pivot(
    index="porte",
    columns="uf",
    values="taxa_inadimplencia"
)

ordem_porte_pj = [
    "Micro",
    "Pequeno",
    "Médio",
    "Grande",
]

matriz_pj = matriz_pj.reindex(ordem_porte_pj)

display(matriz_pj.style.format("{:.2f}%"))

## score de expansão sustentável

In [19]:
# calculo oficial do score de expansao sustentavel.
# esta e a metodologia usada no dashboard (ver docs/metodologia-score.md
# e backend/src/database/queries/ranking.js).
#
# componentes:
#   qualidade   -> 1 - (inadimplencia / carteira ativa)
#   solidez     -> 1 - (ativo problematico / carteira ativa)
#   dinamismo   -> crescimento da carteira ativa de janeiro ate dezembro
#   eficiencia  -> carteira ativa / numero de operacoes (ticket medio)
#
# pesos: qualidade 35%, solidez 30%, dinamismo 25%, eficiencia 10%

import numpy as np
import pandas as pd

# agrupa os dados por estado e mes.
base_estado_data = (
    dt.groupby(["uf", "data_base"], as_index=False)
    .agg({
        "carteira_ativa": "sum",
        "carteira_inadimplencia": "sum",
        "ativo_problematico": "sum",
        "numero_de_operacoes": "sum",
    })
)

base_estado_data = base_estado_data.sort_values(["uf", "data_base"])

# periodo atual = ultimo mes disponivel (dezembro).
periodo_atual = (
    base_estado_data
    .groupby("uf", as_index=False)
    .last()
    .rename(columns={
        "data_base": "data_atual",
        "carteira_ativa": "carteira_ativa_atual",
        "carteira_inadimplencia": "carteira_inadimplencia_atual",
        "ativo_problematico": "ativo_problematico_atual",
        "numero_de_operacoes": "numero_de_operacoes_atual",
    })
)

# periodo anterior = primeiro mes disponivel (janeiro).
periodo_anterior = (
    base_estado_data
    .groupby("uf", as_index=False)
    .first()
    .rename(columns={
        "data_base": "data_anterior",
        "carteira_ativa": "carteira_ativa_anterior",
        "carteira_inadimplencia": "carteira_inadimplencia_anterior",
        "ativo_problematico": "ativo_problematico_anterior",
        "numero_de_operacoes": "numero_de_operacoes_anterior",
    })
)

score_estados_oficial = periodo_atual.merge(
    periodo_anterior,
    on="uf",
    how="inner"
)

# evita divisoes por zero.
score_estados_oficial = score_estados_oficial[
    (score_estados_oficial["carteira_ativa_atual"] > 0) &
    (score_estados_oficial["carteira_ativa_anterior"] > 0) &
    (score_estados_oficial["numero_de_operacoes_atual"] > 0)
].copy()

# qualidade: quanto menor a inadimplencia, maior o score.
score_estados_oficial["qualidade"] = (
    1 - (
        score_estados_oficial["carteira_inadimplencia_atual"]
        / score_estados_oficial["carteira_ativa_atual"]
    )
)

# solidez: quanto menor o ativo problematico, maior o score.
score_estados_oficial["solidez"] = (
    1 - (
        score_estados_oficial["ativo_problematico_atual"]
        / score_estados_oficial["carteira_ativa_atual"]
    )
)

# dinamismo: crescimento da carteira ativa entre janeiro e dezembro.
score_estados_oficial["dinamismo"] = (
    (
        score_estados_oficial["carteira_ativa_atual"]
        - score_estados_oficial["carteira_ativa_anterior"]
    )
    / score_estados_oficial["carteira_ativa_anterior"]
)

# eficiencia: ticket medio (carteira ativa por operacao).
score_estados_oficial["eficiencia"] = (
    score_estados_oficial["carteira_ativa_atual"]
    / score_estados_oficial["numero_de_operacoes_atual"]
)

# normaliza um componente para escala de 0 a 100 via z-score.
def normalizar_componente(serie):
    media = serie.mean()
    desvio = serie.std(ddof=0)

    if desvio == 0:
        return pd.Series(100, index=serie.index)

    z_score = (serie - media) / desvio

    z_min = z_score.min()
    z_max = z_score.max()

    if z_max == z_min:
        return pd.Series(100, index=serie.index)

    return ((z_score - z_min) / (z_max - z_min)) * 100

score_estados_oficial["qualidade_norm"] = normalizar_componente(score_estados_oficial["qualidade"])
score_estados_oficial["solidez_norm"] = normalizar_componente(score_estados_oficial["solidez"])
score_estados_oficial["dinamismo_norm"] = normalizar_componente(score_estados_oficial["dinamismo"])
score_estados_oficial["eficiencia_norm"] = normalizar_componente(score_estados_oficial["eficiencia"])

# score final ponderado (0 a 100).
score_estados_oficial["score_final"] = (
    score_estados_oficial["qualidade_norm"] * 0.35
    + score_estados_oficial["solidez_norm"] * 0.30
    + score_estados_oficial["dinamismo_norm"] * 0.25
    + score_estados_oficial["eficiencia_norm"] * 0.10
)

# ranking final, ordenado do maior para o menor score.
ranking_expansao_oficial = (
    score_estados_oficial
    .sort_values("score_final", ascending=False)
    .reset_index(drop=True)
)

ranking_expansao_oficial["posicao"] = ranking_expansao_oficial.index + 1

ranking_expansao_oficial = ranking_expansao_oficial[[
    "posicao",
    "uf",
    "score_final",
    "qualidade_norm",
    "solidez_norm",
    "dinamismo_norm",
    "eficiencia_norm",
    "qualidade",
    "solidez",
    "dinamismo",
    "eficiencia",
    "carteira_ativa_atual",
    "carteira_ativa_anterior",
    "data_anterior",
    "data_atual",
]].copy()

display(ranking_expansao_oficial)

,posicao,uf,score_final,qualidade_norm,solidez_norm,dinamismo_norm,eficiencia_norm,qualidade,solidez,dinamismo,eficiencia,carteira_ativa_atual,carteira_ativa_anterior,data_anterior,data_atual
0,1,SP,84.899126,95.489836,79.760510,95.569892,36.570573,0.967625,0.932634,0.173754,9389.409498,2.192362e+12,1.867821e+12,2025-01-31,2025-12-31
1,2,SC,78.213029,96.468321,97.169260,40.720502,51.182136,0.968074,0.943132,0.097053,11186.177521,3.919637e+11,3.572879e+11,2025-01-31,2025-12-31
2,3,DF,73.817936,100.000000,100.000000,13.741837,53.824769,0.969696,0.944838,0.059326,11511.139188,1.694249e+11,1.599365e+11,2025-01-31,2025-12-31
3,4,ES,68.504867,86.560590,68.393636,60.671906,25.22593,0.963524,0.925780,0.124953,7994.371014,1.235319e+11,1.098108e+11,2025-01-31,2025-12-31
4,5,PR,66.589338,83.377976,78.285319,38.270542,43.538157,0.962062,0.931745,0.093627,10246.205797,5.373201e+11,4.913194e+11,2025-01-31,2025-12-31
5,6,RS,64.855712,77.898343,68.808706,53.525961,35.671895,0.959546,0.926031,0.114960,9278.90007,5.165961e+11,4.633315e+11,2025-01-31,2025-12-31
6,7,AM,64.792506,57.960906,67.330719,93.235879,9.980034,0.950390,0.925139,0.170490,6119.599842,7.602753e+10,6.495358e+10,2025-01-31,2025-12-31
7,8,PI,60.297305,71.389396,74.273783,48.060135,10.138483,0.956557,0.929326,0.107316,6139.084064,6.332587e+10,5.718859e+10,2025-01-31,2025-12-31
8,9,MG,59.005364,77.327858,73.939293,29.744802,23.22625,0.959284,0.929124,0.081704,7748.472564,6.325402e+11,5.847626e+11,2025-01-31,2025-12-31
9,10,CE,58.633983,63.638965,64.283618,66.689375,4.029164,0.952997,0.923302,0.133368,5387.827811,1.614964e+11,1.424925e+11,2025-01-31,2025-12-31
10,11,AP,57.315183,55.211072,51.245624,82.498283,19.930502,0.949127,0.915440,0.155475,7343.198,1.833766e+10,1.587024e+10,2025-01-31,2025-12-31
11,12,RR,56.956177,47.343856,52.737971,97.177092,2.701631,0.945514,0.916340,0.176002,5224.582441,1.539286e+10,1.308915e+10,2025-01-31,2025-12-31
12,13,PE,52.359629,58.913359,60.454722,53.834002,1.450358,0.950827,0.920993,0.115391,5070.714804,1.631096e+11,1.462354e+11,2025-01-31,2025-12-31
13,14,SE,50.615889,57.066965,55.941849,54.883408,1.390446,0.949979,0.918272,0.116858,5063.347448,4.370124e+10,3.912873e+10,2025-01-31,2025-12-31
14,15,AC,49.703857,57.554953,60.028147,39.517303,16.71854,0.950203,0.920736,0.095370,6948.226516,1.869736e+10,1.706945e+10,2025-01-31,2025-12-31
15,16,AL,49.40485,55.373161,56.458224,52.347108,0.0,0.949201,0.918583,0.113311,4892.365855,5.646625e+10,5.071919e+10,2025-01-31,2025-12-31
16,17,BA,48.201135,59.780107,57.684409,38.251298,4.099506,0.951225,0.919323,0.093600,5396.477637,2.718438e+11,2.485770e+11,2025-01-31,2025-12-31
17,18,PA,47.947527,48.617052,52.037059,57.665793,9.039924,0.946098,0.915918,0.120749,6003.99555,1.560704e+11,1.392554e+11,2025-01-31,2025-12-31
18,19,RN,47.418525,58.127315,53.397363,42.989218,3.074508,0.950466,0.916738,0.100225,5270.434744,6.727312e+10,6.114486e+10,2025-01-31,2025-12-31
19,20,RJ,47.036582,79.205994,57.897972,0.000000,19.450924,0.960146,0.919452,0.040109,7284.224887,5.340927e+11,5.134968e+11,2025-01-31,2025-12-31
20,21,PB,44.001703,46.035666,44.511809,56.757286,3.463563,0.944913,0.911380,0.119479,5318.276452,7.223354e+10,6.452427e+10,2025-01-31,2025-12-31
21,22,MT,42.687842,48.833619,36.515341,18.565893,100.0,0.946198,0.906558,0.066072,17189.257259,2.558127e+11,2.399582e+11,2025-01-31,2025-12-31
22,23,GO,35.279404,38.663038,22.967287,38.012145,53.541185,0.941527,0.898389,0.093265,11476.267256,3.301673e+11,3.020011e+11,2025-01-31,2025-12-31
23,24,RO,35.032477,41.443440,38.358185,20.167976,39.778239,0.942804,0.907669,0.068312,9783.852711,6.220092e+10,5.822355e+10,2025-01-31,2025-12-31
24,25,TO,34.94525,11.041042,5.456810,100.000000,44.438426,0.928842,0.887830,0.179949,10356.910859,5.593609e+10,4.740551e+10,2025-01-31,2025-12-31
25,26,MS,26.235402,38.191751,10.662575,19.214617,48.658624,0.941311,0.890969,0.066979,10875.864002,1.368505e+11,1.282598e+11,2025-01-31,2025-12-31
26,27,MA,13.927957,0.000000,0.000000,53.970538,4.353227,0.923771,0.884540,0.115582,5427.677409,1.085140e+11,9.727125e+10,2025-01-31,2025-12-31

In [20]:
# versao formatada para leitura humana do ranking oficial de expansao.
# percentuais em "%", valores monetarios abreviados (ex: R$ 1,23B).
# este e o ranking exibido na pagina de expansao do dashboard.

ranking_expansao_oficial_formatado = ranking_expansao_oficial.copy()

ranking_expansao_oficial_formatado["score_final"] = ranking_expansao_oficial_formatado["score_final"].map(lambda x: f"{x:.2f}")
ranking_expansao_oficial_formatado["qualidade_norm"] = ranking_expansao_oficial_formatado["qualidade_norm"].map(lambda x: f"{x:.2f}")
ranking_expansao_oficial_formatado["solidez_norm"] = ranking_expansao_oficial_formatado["solidez_norm"].map(lambda x: f"{x:.2f}")
ranking_expansao_oficial_formatado["dinamismo_norm"] = ranking_expansao_oficial_formatado["dinamismo_norm"].map(lambda x: f"{x:.2f}")
ranking_expansao_oficial_formatado["eficiencia_norm"] = ranking_expansao_oficial_formatado["eficiencia_norm"].map(lambda x: f"{x:.2f}")

ranking_expansao_oficial_formatado["qualidade"] = ranking_expansao_oficial_formatado["qualidade"].map(lambda x: f"{x:.2%}")
ranking_expansao_oficial_formatado["solidez"] = ranking_expansao_oficial_formatado["solidez"].map(lambda x: f"{x:.2%}")
ranking_expansao_oficial_formatado["dinamismo"] = ranking_expansao_oficial_formatado["dinamismo"].map(lambda x: f"{x:.2%}")

ranking_expansao_oficial_formatado["eficiencia"] = ranking_expansao_oficial_formatado["eficiencia"].apply(formatar_dinheiro)
ranking_expansao_oficial_formatado["carteira_ativa_atual"] = ranking_expansao_oficial_formatado["carteira_ativa_atual"].apply(formatar_dinheiro)
ranking_expansao_oficial_formatado["carteira_ativa_anterior"] = ranking_expansao_oficial_formatado["carteira_ativa_anterior"].apply(formatar_dinheiro)

display(ranking_expansao_oficial_formatado)

,posicao,uf,score_final,qualidade_norm,solidez_norm,dinamismo_norm,eficiencia_norm,qualidade,solidez,dinamismo,eficiencia,carteira_ativa_atual,carteira_ativa_anterior,data_anterior,data_atual
0,1,SP,84.90,95.49,79.76,95.57,36.57,96.76%,93.26%,17.38%,"R$ 9,39K","R$ 2,19T","R$ 1,87T",2025-01-31,2025-12-31
1,2,SC,78.21,96.47,97.17,40.72,51.18,96.81%,94.31%,9.71%,"R$ 11,19K","R$ 391,96B","R$ 357,29B",2025-01-31,2025-12-31
2,3,DF,73.82,100.00,100.00,13.74,53.82,96.97%,94.48%,5.93%,"R$ 11,51K","R$ 169,42B","R$ 159,94B",2025-01-31,2025-12-31
3,4,ES,68.50,86.56,68.39,60.67,25.23,96.35%,92.58%,12.50%,"R$ 7,99K","R$ 123,53B","R$ 109,81B",2025-01-31,2025-12-31
4,5,PR,66.59,83.38,78.29,38.27,43.54,96.21%,93.17%,9.36%,"R$ 10,25K","R$ 537,32B","R$ 491,32B",2025-01-31,2025-12-31
5,6,RS,64.86,77.90,68.81,53.53,35.67,95.95%,92.60%,11.50%,"R$ 9,28K","R$ 516,60B","R$ 463,33B",2025-01-31,2025-12-31
6,7,AM,64.79,57.96,67.33,93.24,9.98,95.04%,92.51%,17.05%,"R$ 6,12K","R$ 76,03B","R$ 64,95B",2025-01-31,2025-12-31
7,8,PI,60.30,71.39,74.27,48.06,10.14,95.66%,92.93%,10.73%,"R$ 6,14K","R$ 63,33B","R$ 57,19B",2025-01-31,2025-12-31
8,9,MG,59.01,77.33,73.94,29.74,23.23,95.93%,92.91%,8.17%,"R$ 7,75K","R$ 632,54B","R$ 584,76B",2025-01-31,2025-12-31
9,10,CE,58.63,63.64,64.28,66.69,4.03,95.30%,92.33%,13.34%,"R$ 5,39K","R$ 161,50B","R$ 142,49B",2025-01-31,2025-12-31
10,11,AP,57.32,55.21,51.25,82.50,19.93,94.91%,91.54%,15.55%,"R$ 7,34K","R$ 18,34B","R$ 15,87B",2025-01-31,2025-12-31
11,12,RR,56.96,47.34,52.74,97.18,2.70,94.55%,91.63%,17.60%,"R$ 5,22K","R$ 15,39B","R$ 13,09B",2025-01-31,2025-12-31
12,13,PE,52.36,58.91,60.45,53.83,1.45,95.08%,92.10%,11.54%,"R$ 5,07K","R$ 163,11B","R$ 146,24B",2025-01-31,2025-12-31
13,14,SE,50.62,57.07,55.94,54.88,1.39,95.00%,91.83%,11.69%,"R$ 5,06K","R$ 43,70B","R$ 39,13B",2025-01-31,2025-12-31
14,15,AC,49.70,57.55,60.03,39.52,16.72,95.02%,92.07%,9.54%,"R$ 6,95K","R$ 18,70B","R$ 17,07B",2025-01-31,2025-12-31
15,16,AL,49.40,55.37,56.46,52.35,0.00,94.92%,91.86%,11.33%,"R$ 4,89K","R$ 56,47B","R$ 50,72B",2025-01-31,2025-12-31
16,17,BA,48.20,59.78,57.68,38.25,4.10,95.12%,91.93%,9.36%,"R$ 5,40K","R$ 271,84B","R$ 248,58B",2025-01-31,2025-12-31
17,18,PA,47.95,48.62,52.04,57.67,9.04,94.61%,91.59%,12.07%,"R$ 6,00K","R$ 156,07B","R$ 139,26B",2025-01-31,2025-12-31
18,19,RN,47.42,58.13,53.40,42.99,3.07,95.05%,91.67%,10.02%,"R$ 5,27K","R$ 67,27B","R$ 61,14B",2025-01-31,2025-12-31
19,20,RJ,47.04,79.21,57.90,0.00,19.45,96.01%,91.95%,4.01%,"R$ 7,28K","R$ 534,09B","R$ 513,50B",2025-01-31,2025-12-31
20,21,PB,44.00,46.04,44.51,56.76,3.46,94.49%,91.14%,11.95%,"R$ 5,32K","R$ 72,23B","R$ 64,52B",2025-01-31,2025-12-31
21,22,MT,42.69,48.83,36.52,18.57,100.00,94.62%,90.66%,6.61%,"R$ 17,19K","R$ 255,81B","R$ 239,96B",2025-01-31,2025-12-31
22,23,GO,35.28,38.66,22.97,38.01,53.54,94.15%,89.84%,9.33%,"R$ 11,48K","R$ 330,17B","R$ 302,00B",2025-01-31,2025-12-31
23,24,RO,35.03,41.44,38.36,20.17,39.78,94.28%,90.77%,6.83%,"R$ 9,78K","R$ 62,20B","R$ 58,22B",2025-01-31,2025-12-31
24,25,TO,34.95,11.04,5.46,100.00,44.44,92.88%,88.78%,17.99%,"R$ 10,36K","R$ 55,94B","R$ 47,41B",2025-01-31,2025-12-31
25,26,MS,26.24,38.19,10.66,19.21,48.66,94.13%,89.10%,6.70%,"R$ 10,88K","R$ 136,85B","R$ 128,26B",2025-01-31,2025-12-31
26,27,MA,13.93,0.00,0.00,53.97,4.35,92.38%,88.45%,11.56%,"R$ 5,43K","R$ 108,51B","R$ 97,27B",2025-01-31,2025-12-31

In [21]:
# exporta o ranking oficial de expansao para excel.
# util para conferencia externa dos dados usados no dashboard.

from google.colab import files

ranking_expansao_oficial_formatado.to_excel("ranking_expansao_oficial.xlsx", index=False)
files.download("ranking_expansao_oficial.xlsx")

## anexo — exploração e versões anteriores

In [22]:
# verificação dos tipos de porte e cliente, feita durante o desenvolvimento
# para conferir a quantidade de registros por combinação de cliente (PF/PJ)
# e porte, validando as categorias descritas na seção de ingestão.

resumo_portes = (
    dt.groupby(["cliente", "porte"])
    .size()
    .reset_index(name="quantidade")
)

display(resumo_portes)

   cliente                             porte  quantidade
0       PF      Acima de 20 salários mínimos         324
1       PF              Até 1 salário mínimo         324
2       PF    Mais de 1 a 2 salários mínimos         324
3       PF  Mais de 10 a 20 salários mínimos         324
4       PF    Mais de 2 a 3 salários mínimos         324
5       PF    Mais de 3 a 5 salários mínimos         324
6       PF   Mais de 5 a 10 salários mínimos         324
7       PF                    Sem rendimento         324
8       PJ                            Grande         324
9       PJ                             Micro         324
10      PJ                             Médio         324
11      PJ                           Pequeno         324

### análise de score — estudo de variações

as células abaixo testam variações da fórmula de score de expansão que
**não foram adotadas** no projeto final. ficam aqui como registro do
processo de estudo e comparação de metodologias.

para o cálculo oficial usado no dashboard, veja a seção
"score de expansão sustentável" acima.

In [23]:
# variacao 1: primeira versao do score, antes do ajuste do dinamismo
# para crescimento ano inteiro (jan-dez).
# diferenca em relacao ao oficial: dinamismo calculado com o mes anterior
# ao ultimo disponivel, nao com janeiro.
#
# obs: esta celula recalcula periodo_atual e periodo_anterior, que passam
# a ser usados pelas duas celulas seguintes (estudo de populacao e de
# eficiencia invertida).

# agrupa os dados por estado e data.
base_estado_data = (
    dt.groupby(["uf", "data_base"], as_index=False)
    .agg({
        "carteira_ativa": "sum",
        "carteira_inadimplencia": "sum",
        "ativo_problematico": "sum",
        "numero_de_operacoes": "sum",
    })
)

# ordena os dados para identificar o periodo atual e o anterior de cada estado.
base_estado_data = base_estado_data.sort_values(["uf", "data_base"])

# periodo atual = ultimo mes disponivel.
periodo_atual = (
    base_estado_data
    .groupby("uf", as_index=False)
    .last()
    .rename(columns={
        "data_base": "data_atual",
        "carteira_ativa": "carteira_ativa_atual",
        "carteira_inadimplencia": "carteira_inadimplencia_atual",
        "ativo_problematico": "ativo_problematico_atual",
        "numero_de_operacoes": "numero_de_operacoes_atual",
    })
)

# periodo anterior = penultimo mes disponivel.
periodo_anterior = (
    base_estado_data
    .groupby("uf")
    .nth(-2)
    .reset_index()
    .rename(columns={
        "data_base": "data_anterior",
        "carteira_ativa": "carteira_ativa_anterior",
        "carteira_inadimplencia": "carteira_inadimplencia_anterior",
        "ativo_problematico": "ativo_problematico_anterior",
        "numero_de_operacoes": "numero_de_operacoes_anterior",
    })
)

# junta o periodo atual com o periodo anterior.
score_estudo_dinamismo_mensal = periodo_atual.merge(
    periodo_anterior,
    on="uf",
    how="inner"
)

# evita divisoes por zero.
score_estudo_dinamismo_mensal = score_estudo_dinamismo_mensal[
    (score_estudo_dinamismo_mensal["carteira_ativa_atual"] > 0) &
    (score_estudo_dinamismo_mensal["carteira_ativa_anterior"] > 0) &
    (score_estudo_dinamismo_mensal["numero_de_operacoes_atual"] > 0)
].copy()

# calcula os 4 componentes brutos do score.
score_estudo_dinamismo_mensal["qualidade"] = (
    1 - (
        score_estudo_dinamismo_mensal["carteira_inadimplencia_atual"]
        / score_estudo_dinamismo_mensal["carteira_ativa_atual"]
    )
)

score_estudo_dinamismo_mensal["solidez"] = (
    1 - (
        score_estudo_dinamismo_mensal["ativo_problematico_atual"]
        / score_estudo_dinamismo_mensal["carteira_ativa_atual"]
    )
)

score_estudo_dinamismo_mensal["dinamismo"] = (
    (
        score_estudo_dinamismo_mensal["carteira_ativa_atual"]
        - score_estudo_dinamismo_mensal["carteira_ativa_anterior"]
    )
    / score_estudo_dinamismo_mensal["carteira_ativa_anterior"]
)

score_estudo_dinamismo_mensal["eficiencia"] = (
    score_estudo_dinamismo_mensal["carteira_ativa_atual"]
    / score_estudo_dinamismo_mensal["numero_de_operacoes_atual"]
)

# normaliza cada componente (reaproveita normalizar_componente da secao oficial).
score_estudo_dinamismo_mensal["qualidade_norm"] = normalizar_componente(score_estudo_dinamismo_mensal["qualidade"])
score_estudo_dinamismo_mensal["solidez_norm"] = normalizar_componente(score_estudo_dinamismo_mensal["solidez"])
score_estudo_dinamismo_mensal["dinamismo_norm"] = normalizar_componente(score_estudo_dinamismo_mensal["dinamismo"])
score_estudo_dinamismo_mensal["eficiencia_norm"] = normalizar_componente(score_estudo_dinamismo_mensal["eficiencia"])

# calcula o score final ponderado.
score_estudo_dinamismo_mensal["score_final"] = (
    score_estudo_dinamismo_mensal["qualidade_norm"] * 0.35
    + score_estudo_dinamismo_mensal["solidez_norm"] * 0.30
    + score_estudo_dinamismo_mensal["dinamismo_norm"] * 0.25
    + score_estudo_dinamismo_mensal["eficiencia_norm"] * 0.10
)

# gera o ranking desta variacao.
ranking_estudo_dinamismo_mensal = (
    score_estudo_dinamismo_mensal
    .sort_values("score_final", ascending=False)
    .reset_index(drop=True)
)

ranking_estudo_dinamismo_mensal["posicao"] = ranking_estudo_dinamismo_mensal.index + 1

ranking_estudo_dinamismo_mensal = ranking_estudo_dinamismo_mensal[[
    "posicao",
    "uf",
    "score_final",
    "qualidade_norm",
    "solidez_norm",
    "dinamismo_norm",
    "eficiencia_norm",
    "qualidade",
    "solidez",
    "dinamismo",
    "eficiencia",
    "carteira_ativa_atual",
    "carteira_ativa_anterior",
    "data_anterior",
    "data_atual",
]].copy()

display(ranking_estudo_dinamismo_mensal)

,posicao,uf,score_final,qualidade_norm,solidez_norm,dinamismo_norm,eficiencia_norm,qualidade,solidez,dinamismo,eficiencia,carteira_ativa_atual,carteira_ativa_anterior,data_anterior,data_atual
0,1,DF,95.382477,100.000000,100.000000,100.000000,53.824769,0.969696,0.944838,0.063504,11511.139188,1.694249e+11,1.593082e+11,2025-11-30,2025-12-31
1,2,SC,75.030793,96.468321,97.169260,27.991556,51.182136,0.968074,0.943132,0.015613,11186.177521,3.919637e+11,3.859381e+11,2025-11-30,2025-12-31
2,3,SP,70.2684,95.489836,79.760510,37.046989,36.570573,0.967625,0.932634,0.021635,9389.409498,2.192362e+12,2.145934e+12,2025-11-30,2025-12-31
3,4,ES,62.523829,86.560590,68.393636,36.747756,25.22593,0.963524,0.925780,0.021436,7994.371014,1.235319e+11,1.209394e+11,2025-11-30,2025-12-31
4,5,PR,62.191519,83.377976,78.285319,20.679265,43.538157,0.962062,0.931745,0.010750,10246.205797,5.373201e+11,5.316055e+11,2025-11-30,2025-12-31
5,6,RS,58.226085,77.898343,68.808706,27.007456,35.671895,0.959546,0.926031,0.014958,9278.90007,5.165961e+11,5.089825e+11,2025-11-30,2025-12-31
6,7,MG,55.441806,77.327858,73.939293,15.490573,23.22625,0.959284,0.929124,0.007299,7748.472564,6.325402e+11,6.279569e+11,2025-11-30,2025-12-31
7,8,RR,50.852063,47.343856,52.737971,72.760638,2.701631,0.945514,0.916340,0.045388,5224.582441,1.539286e+10,1.472454e+10,2025-11-30,2025-12-31
8,9,RJ,50.739161,79.205994,57.897972,14.810315,19.450924,0.960146,0.919452,0.006846,7284.224887,5.340927e+11,5.304610e+11,2025-11-30,2025-12-31
9,10,AM,48.976447,57.960906,67.330719,29.971645,9.980034,0.950390,0.925139,0.016930,6119.599842,7.602753e+10,7.476182e+10,2025-11-30,2025-12-31
10,11,PI,48.282272,71.389396,74.273783,0.000000,10.138483,0.956557,0.929326,-0.003004,6139.084064,6.332587e+10,6.351665e+10,2025-11-30,2025-12-31
11,12,MT,45.800764,48.833619,36.515341,31.017580,100.0,0.946198,0.906558,0.017625,17189.257259,2.558127e+11,2.513820e+11,2025-11-30,2025-12-31
12,13,BA,45.26725,59.780107,57.684409,26.515758,4.099506,0.951225,0.919323,0.014631,5396.477637,2.718438e+11,2.679237e+11,2025-11-30,2025-12-31
13,14,CE,45.033104,63.638965,64.283618,12.285858,4.029164,0.952997,0.923302,0.005167,5387.827811,1.614964e+11,1.606661e+11,2025-11-30,2025-12-31
14,15,PE,44.023084,58.913359,60.454722,20.487823,1.450358,0.950827,0.920993,0.010622,5070.714804,1.631096e+11,1.613952e+11,2025-11-30,2025-12-31
15,16,AC,42.352707,57.554953,60.028147,10.112701,16.71854,0.950203,0.920736,0.003722,6948.226516,1.869736e+10,1.862803e+10,2025-11-30,2025-12-31
16,17,SE,40.813238,57.066965,55.941849,15.672804,1.390446,0.949979,0.918272,0.007420,5063.347448,4.370124e+10,4.337937e+10,2025-11-30,2025-12-31
17,18,AP,40.765333,55.211072,51.245624,16.298880,19.930502,0.949127,0.915440,0.007836,7343.198,1.833766e+10,1.819508e+10,2025-11-30,2025-12-31
18,19,AL,38.901999,55.373161,56.458224,10.335703,0.0,0.949201,0.918583,0.003870,4892.365855,5.646625e+10,5.624855e+10,2025-11-30,2025-12-31
19,20,PA,38.056931,48.617052,52.037059,18.103409,9.039924,0.946098,0.915918,0.009037,6003.99555,1.560704e+11,1.546727e+11,2025-11-30,2025-12-31
20,21,RN,37.646201,58.127315,53.397363,3.899925,3.074508,0.950466,0.916738,-0.000410,5270.434744,6.727312e+10,6.730070e+10,2025-11-30,2025-12-31
21,22,RO,32.378056,41.443440,38.358185,9.550292,39.778239,0.942804,0.907669,0.003348,9783.852711,6.220092e+10,6.199336e+10,2025-11-30,2025-12-31
22,23,PB,31.724677,46.035666,44.511809,7.649179,3.463563,0.944913,0.911380,0.002084,5318.276452,7.223354e+10,7.208334e+10,2025-11-30,2025-12-31
23,24,GO,30.38127,38.663038,22.967287,18.419610,53.541185,0.941527,0.898389,0.009247,11476.267256,3.301673e+11,3.271423e+11,2025-11-30,2025-12-31
24,25,MS,24.929082,38.191751,10.662575,13.989337,48.658624,0.941311,0.890969,0.006300,10875.864002,1.368505e+11,1.359937e+11,2025-11-30,2025-12-31
25,26,TO,17.133582,11.041042,5.456810,28.753327,44.438426,0.928842,0.887830,0.016120,10356.910859,5.593609e+10,5.504873e+10,2025-11-30,2025-12-31
26,27,MA,1.210614,0.000000,0.000000,3.101165,4.353227,0.923771,0.884540,-0.000941,5427.677409,1.085140e+11,1.086162e+11,2025-11-30,2025-12-31

In [24]:
# variacao 2: score com fator de oportunidade populacional (censo IBGE 2022).
# adiciona um quinto componente, que beneficia estados com menor carteira
# ativa por habitante (maior espaco para credito crescer).
#
# obs: usa periodo_atual e periodo_anterior calculados na celula anterior
# (base mensal, nao ano inteiro).

populacao_uf = {
    "RO": 1581196,
    "AC": 830018,
    "AM": 3941613,
    "RR": 636303,
    "PA": 8121025,
    "AP": 733759,
    "TO": 1511459,
    "MA": 6775152,
    "PI": 3271199,
    "CE": 8794957,
    "RN": 3302729,
    "PB": 3974687,
    "PE": 9058155,
    "AL": 3127511,
    "SE": 2209558,
    "BA": 14136417,
    "MG": 20539989,
    "ES": 3833486,
    "RJ": 16054524,
    "SP": 44411238,
    "PR": 11444380,
    "SC": 7610361,
    "RS": 10882965,
    "MS": 2756700,
    "MT": 3658649,
    "GO": 7056495,
    "DF": 2817381,
}

score_estudo_oportunidade_populacional = periodo_atual.merge(
    periodo_anterior,
    on="uf",
    how="inner"
)

score_estudo_oportunidade_populacional["populacao"] = score_estudo_oportunidade_populacional["uf"].map(populacao_uf)

score_estudo_oportunidade_populacional = score_estudo_oportunidade_populacional[
    (score_estudo_oportunidade_populacional["carteira_ativa_atual"] > 0) &
    (score_estudo_oportunidade_populacional["carteira_ativa_anterior"] > 0) &
    (score_estudo_oportunidade_populacional["numero_de_operacoes_atual"] > 0) &
    (score_estudo_oportunidade_populacional["populacao"] > 0)
].copy()

score_estudo_oportunidade_populacional["qualidade"] = (
    1 - (
        score_estudo_oportunidade_populacional["carteira_inadimplencia_atual"]
        / score_estudo_oportunidade_populacional["carteira_ativa_atual"]
    )
)

score_estudo_oportunidade_populacional["solidez"] = (
    1 - (
        score_estudo_oportunidade_populacional["ativo_problematico_atual"]
        / score_estudo_oportunidade_populacional["carteira_ativa_atual"]
    )
)

score_estudo_oportunidade_populacional["dinamismo"] = (
    (
        score_estudo_oportunidade_populacional["carteira_ativa_atual"]
        - score_estudo_oportunidade_populacional["carteira_ativa_anterior"]
    )
    / score_estudo_oportunidade_populacional["carteira_ativa_anterior"]
)

score_estudo_oportunidade_populacional["eficiencia"] = (
    score_estudo_oportunidade_populacional["carteira_ativa_atual"]
    / score_estudo_oportunidade_populacional["numero_de_operacoes_atual"]
)

# carteira ativa por habitante: quanto menor, maior a oportunidade.
score_estudo_oportunidade_populacional["carteira_por_habitante"] = (
    score_estudo_oportunidade_populacional["carteira_ativa_atual"]
    / score_estudo_oportunidade_populacional["populacao"]
)

score_estudo_oportunidade_populacional["oportunidade_populacional"] = (
    score_estudo_oportunidade_populacional["carteira_por_habitante"] * -1
)

score_estudo_oportunidade_populacional["qualidade_norm"] = normalizar_componente(score_estudo_oportunidade_populacional["qualidade"])
score_estudo_oportunidade_populacional["solidez_norm"] = normalizar_componente(score_estudo_oportunidade_populacional["solidez"])
score_estudo_oportunidade_populacional["dinamismo_norm"] = normalizar_componente(score_estudo_oportunidade_populacional["dinamismo"])
score_estudo_oportunidade_populacional["eficiencia_norm"] = normalizar_componente(score_estudo_oportunidade_populacional["eficiencia"])
score_estudo_oportunidade_populacional["oportunidade_populacional_norm"] = normalizar_componente(score_estudo_oportunidade_populacional["oportunidade_populacional"])

# pesos redistribuidos para abrir espaco ao novo componente (15%).
score_estudo_oportunidade_populacional["score_final"] = (
    score_estudo_oportunidade_populacional["qualidade_norm"] * 0.30
    + score_estudo_oportunidade_populacional["solidez_norm"] * 0.25
    + score_estudo_oportunidade_populacional["dinamismo_norm"] * 0.20
    + score_estudo_oportunidade_populacional["eficiencia_norm"] * 0.10
    + score_estudo_oportunidade_populacional["oportunidade_populacional_norm"] * 0.15
)

ranking_estudo_oportunidade_populacional = (
    score_estudo_oportunidade_populacional
    .sort_values("score_final", ascending=False)
    .reset_index(drop=True)
)

ranking_estudo_oportunidade_populacional["posicao"] = ranking_estudo_oportunidade_populacional.index + 1

ranking_estudo_oportunidade_populacional = ranking_estudo_oportunidade_populacional[[
    "posicao",
    "uf",
    "score_final",
    "qualidade_norm",
    "solidez_norm",
    "dinamismo_norm",
    "eficiencia_norm",
    "oportunidade_populacional_norm",
    "qualidade",
    "solidez",
    "dinamismo",
    "eficiencia",
    "carteira_por_habitante",
    "populacao",
    "carteira_ativa_atual",
    "carteira_ativa_anterior",
    "data_anterior",
    "data_atual",
]].copy()

display(ranking_estudo_oportunidade_populacional)

,posicao,uf,score_final,qualidade_norm,solidez_norm,dinamismo_norm,eficiencia_norm,oportunidade_populacional_norm,qualidade,solidez,dinamismo,eficiencia,carteira_por_habitante,populacao,carteira_ativa_atual,carteira_ativa_anterior,data_anterior,data_atual
0,1,DF,83.105228,100.000000,100.000000,100.000000,53.824769,18.151677,0.969696,0.944838,0.063504,11511.139188,60135.591126,2817381,1.694249e+11,1.593082e+11,2025-11-30,2025-12-31
1,2,SC,69.074056,96.468321,97.169260,27.991556,51.182136,34.164803,0.968074,0.943132,0.015613,11186.177521,51503.953978,7610361,3.919637e+11,3.859381e+11,2025-11-30,2025-12-31
2,3,SP,65.373461,95.489836,79.760510,37.046989,36.570573,38.132851,0.967625,0.932634,0.021635,9389.409498,49365.036763,44411238,2.192362e+12,2.145934e+12,2025-11-30,2025-12-31
3,4,ES,63.428459,86.560590,68.393636,36.747756,25.22593,69.931530,0.963524,0.925780,0.021436,7994.371014,32224.431463,3833486,1.235319e+11,1.209394e+11,2025-11-30,2025-12-31
4,5,PR,59.466207,83.377976,78.285319,20.679265,43.538157,42.612104,0.962062,0.931745,0.010750,10246.205797,46950.561688,11444380,5.373201e+11,5.316055e+11,2025-11-30,2025-12-31
5,6,MG,57.991272,77.327858,73.939293,15.490573,23.22625,72.582347,0.959284,0.929124,0.007299,7748.472564,30795.548115,20539989,6.325402e+11,6.279569e+11,2025-11-30,2025-12-31
6,7,RS,55.788097,77.898343,68.808706,27.007456,35.671895,41.651578,0.959546,0.926031,0.014958,9278.90007,47468.318858,10882965,5.165961e+11,5.089825e+11,2025-11-30,2025-12-31
7,8,AM,55.302779,57.960906,67.330719,29.971645,9.980034,93.929968,0.950390,0.925139,0.016930,6119.599842,19288.430375,3941613,7.602753e+10,7.476182e+10,2025-11-30,2025-12-31
8,9,PI,55.069078,71.389396,74.273783,0.000000,10.138483,93.799772,0.956557,0.929326,-0.003004,6139.084064,19358.610606,3271199,6.332587e+10,6.351665e+10,2025-11-30,2025-12-31
9,10,RR,54.93515,47.343856,52.737971,72.760638,2.701631,84.834732,0.945514,0.916340,0.045388,5224.582441,24191.082074,636303,1.539286e+10,1.472454e+10,2025-11-30,2025-12-31
10,11,RJ,53.342936,79.205994,57.897972,14.810315,19.450924,67.996596,0.960146,0.919452,0.006846,7284.224887,33267.428872,16054524,5.340927e+11,5.304610e+11,2025-11-30,2025-12-31
11,12,CE,52.369873,63.638965,64.283618,12.285858,4.029164,95.647938,0.952997,0.923302,0.005167,5387.827811,18362.384027,8794957,1.614964e+11,1.606661e+11,2025-11-30,2025-12-31
12,13,BA,52.173982,59.780107,57.684409,26.515758,4.099506,94.038307,0.951225,0.919323,0.014631,5396.477637,19230.031984,14136417,2.718438e+11,2.679237e+11,2025-11-30,2025-12-31
13,14,PE,51.476393,58.913359,60.454722,20.487823,1.450358,96.307361,0.950827,0.920993,0.010622,5070.714804,18006.932062,9058155,1.631096e+11,1.613952e+11,2025-11-30,2025-12-31
14,15,AC,49.15635,57.554953,60.028147,10.112701,16.71854,87.922889,0.950203,0.920736,0.003722,6948.226516,22526.457117,830018,1.869736e+10,1.862803e+10,2025-11-30,2025-12-31
15,16,SE,48.332341,57.066965,55.941849,15.672804,1.390446,93.021229,0.949979,0.918272,0.007420,5063.347448,19778.272589,2209558,4.370124e+10,4.337937e+10,2025-11-30,2025-12-31
16,17,AL,47.226458,55.373161,56.458224,10.335703,0.0,96.218755,0.949201,0.918583,0.003870,4892.365855,18054.693728,3127511,5.646625e+10,5.624855e+10,2025-11-30,2025-12-31
17,18,AP,47.130056,55.211072,51.245624,16.298880,19.930502,83.350017,0.949127,0.915440,0.007836,7343.198,24991.395928,733759,1.833766e+10,1.819508e+10,2025-11-30,2025-12-31
18,19,PA,46.22813,48.617052,52.037059,18.103409,9.039924,94.060503,0.946098,0.915918,0.009037,6003.99555,19218.067428,8121025,1.560704e+11,1.546727e+11,2025-11-30,2025-12-31
19,20,RN,45.663785,58.127315,53.397363,3.899925,3.074508,91.925425,0.950466,0.916738,-0.000410,5270.434744,20368.949533,3302729,6.727312e+10,6.730070e+10,2025-11-30,2025-12-31
20,21,PB,41.214627,46.035666,44.511809,7.649179,3.463563,95.998553,0.944913,0.911380,0.002084,5318.276452,18173.390283,3974687,7.223354e+10,7.208334e+10,2025-11-30,2025-12-31
21,22,MT,39.982437,48.833619,36.515341,31.017580,100.0,0.000000,0.946198,0.906558,0.017625,17189.257259,69919.982808,3658649,2.558127e+11,2.513820e+11,2025-11-30,2025-12-31
22,23,RO,36.420691,41.443440,38.358185,9.550292,39.778239,56.734870,0.942804,0.907669,0.003348,9783.852711,39337.894784,1581196,6.220092e+10,6.199336e+10,2025-11-30,2025-12-31
23,24,GO,32.81551,38.663038,22.967287,18.419610,53.541185,42.911578,0.941527,0.898389,0.009247,11476.267256,46789.134989,7056495,3.301673e+11,3.271423e+11,2025-11-30,2025-12-31
24,25,MS,27.429509,38.191751,10.662575,13.989337,48.658624,37.617404,0.941311,0.890969,0.006300,10875.864002,49642.880647,2756700,1.368505e+11,1.359937e+11,2025-11-30,2025-12-31
25,26,TO,24.029602,11.041042,5.456810,28.753327,44.438426,61.057193,0.928842,0.887830,0.016120,10356.910859,37008.010766,1511459,5.593609e+10,5.504873e+10,2025-11-30,2025-12-31
26,27,MA,16.055556,0.000000,0.000000,3.101165,4.353227,100.000000,0.923771,0.884540,-0.000941,5427.677409,16016.469948,6775152,1.085140e+11,1.086162e+11,2025-11-30,2025-12-31

In [25]:
# variacao 3: score com eficiencia invertida.
# beneficia estados com menor carteira ativa por operacao (ticket medio
# menor), ao inves do oficial, que beneficia ticket medio maior.
#
# obs: usa periodo_atual e periodo_anterior calculados na celula da
# variacao 1 (base mensal).

score_estudo_eficiencia_invertida = periodo_atual.merge(
    periodo_anterior,
    on="uf",
    how="inner"
)

score_estudo_eficiencia_invertida = score_estudo_eficiencia_invertida[
    (score_estudo_eficiencia_invertida["carteira_ativa_atual"] > 0) &
    (score_estudo_eficiencia_invertida["carteira_ativa_anterior"] > 0) &
    (score_estudo_eficiencia_invertida["numero_de_operacoes_atual"] > 0)
].copy()

score_estudo_eficiencia_invertida["qualidade"] = (
    1 - (
        score_estudo_eficiencia_invertida["carteira_inadimplencia_atual"]
        / score_estudo_eficiencia_invertida["carteira_ativa_atual"]
    )
)

score_estudo_eficiencia_invertida["solidez"] = (
    1 - (
        score_estudo_eficiencia_invertida["ativo_problematico_atual"]
        / score_estudo_eficiencia_invertida["carteira_ativa_atual"]
    )
)

score_estudo_eficiencia_invertida["dinamismo"] = (
    (
        score_estudo_eficiencia_invertida["carteira_ativa_atual"]
        - score_estudo_eficiencia_invertida["carteira_ativa_anterior"]
    )
    / score_estudo_eficiencia_invertida["carteira_ativa_anterior"]
)

score_estudo_eficiencia_invertida["eficiencia"] = (
    score_estudo_eficiencia_invertida["carteira_ativa_atual"]
    / score_estudo_eficiencia_invertida["numero_de_operacoes_atual"]
)

# inverte a eficiencia: agora, ticket medio menor = score maior.
score_estudo_eficiencia_invertida["eficiencia_invertida"] = (
    score_estudo_eficiencia_invertida["eficiencia"] * -1
)

score_estudo_eficiencia_invertida["qualidade_norm"] = normalizar_componente(score_estudo_eficiencia_invertida["qualidade"])
score_estudo_eficiencia_invertida["solidez_norm"] = normalizar_componente(score_estudo_eficiencia_invertida["solidez"])
score_estudo_eficiencia_invertida["dinamismo_norm"] = normalizar_componente(score_estudo_eficiencia_invertida["dinamismo"])
score_estudo_eficiencia_invertida["eficiencia_invertida_norm"] = normalizar_componente(score_estudo_eficiencia_invertida["eficiencia_invertida"])

score_estudo_eficiencia_invertida["score_final"] = (
    score_estudo_eficiencia_invertida["qualidade_norm"] * 0.35
    + score_estudo_eficiencia_invertida["solidez_norm"] * 0.30
    + score_estudo_eficiencia_invertida["dinamismo_norm"] * 0.25
    + score_estudo_eficiencia_invertida["eficiencia_invertida_norm"] * 0.10
)

ranking_estudo_eficiencia_invertida = (
    score_estudo_eficiencia_invertida
    .sort_values("score_final", ascending=False)
    .reset_index(drop=True)
)

ranking_estudo_eficiencia_invertida["posicao"] = ranking_estudo_eficiencia_invertida.index + 1

ranking_estudo_eficiencia_invertida = ranking_estudo_eficiencia_invertida[[
    "posicao",
    "uf",
    "score_final",
    "qualidade_norm",
    "solidez_norm",
    "dinamismo_norm",
    "eficiencia_invertida_norm",
    "qualidade",
    "solidez",
    "dinamismo",
    "eficiencia",
    "eficiencia_invertida",
    "carteira_ativa_atual",
    "carteira_ativa_anterior",
    "data_anterior",
    "data_atual",
]].copy()

display(ranking_estudo_eficiencia_invertida)

,posicao,uf,score_final,qualidade_norm,solidez_norm,dinamismo_norm,eficiencia_invertida_norm,qualidade,solidez,dinamismo,eficiencia,eficiencia_invertida,carteira_ativa_atual,carteira_ativa_anterior,data_anterior,data_atual
0,1,DF,94.617523,100.000000,100.000000,100.000000,46.175231,0.969696,0.944838,0.063504,11511.139188,-11511.139188,1.694249e+11,1.593082e+11,2025-11-30,2025-12-31
1,2,SC,74.794366,96.468321,97.169260,27.991556,48.817864,0.968074,0.943132,0.015613,11186.177521,-11186.177521,3.919637e+11,3.859381e+11,2025-11-30,2025-12-31
2,3,SP,72.954285,95.489836,79.760510,37.046989,63.429427,0.967625,0.932634,0.021635,9389.409498,-9389.409498,2.192362e+12,2.145934e+12,2025-11-30,2025-12-31
3,4,ES,67.478643,86.560590,68.393636,36.747756,74.77407,0.963524,0.925780,0.021436,7994.371014,-7994.371014,1.235319e+11,1.209394e+11,2025-11-30,2025-12-31
4,5,PR,63.483888,83.377976,78.285319,20.679265,56.461843,0.962062,0.931745,0.010750,10246.205797,-10246.205797,5.373201e+11,5.316055e+11,2025-11-30,2025-12-31
5,6,RS,61.091706,77.898343,68.808706,27.007456,64.328105,0.959546,0.926031,0.014958,9278.90007,-9278.90007,5.165961e+11,5.089825e+11,2025-11-30,2025-12-31
6,7,MG,60.796557,77.327858,73.939293,15.490573,76.77375,0.959284,0.929124,0.007299,7748.472564,-7748.472564,6.325402e+11,6.279569e+11,2025-11-30,2025-12-31
7,8,RR,60.311737,47.343856,52.737971,72.760638,97.298369,0.945514,0.916340,0.045388,5224.582441,-5224.582441,1.539286e+10,1.472454e+10,2025-11-30,2025-12-31
8,9,AM,56.980441,57.960906,67.330719,29.971645,90.019966,0.950390,0.925139,0.016930,6119.599842,-6119.599842,7.602753e+10,7.476182e+10,2025-11-30,2025-12-31
9,10,RJ,56.848976,79.205994,57.897972,14.810315,80.549076,0.960146,0.919452,0.006846,7284.224887,-7284.224887,5.340927e+11,5.304610e+11,2025-11-30,2025-12-31
10,11,PI,56.254575,71.389396,74.273783,0.000000,89.861517,0.956557,0.929326,-0.003004,6139.084064,-6139.084064,6.332587e+10,6.351665e+10,2025-11-30,2025-12-31
11,12,BA,54.447349,59.780107,57.684409,26.515758,95.900494,0.951225,0.919323,0.014631,5396.477637,-5396.477637,2.718438e+11,2.679237e+11,2025-11-30,2025-12-31
12,13,CE,54.227271,63.638965,64.283618,12.285858,95.970836,0.952997,0.923302,0.005167,5387.827811,-5387.827811,1.614964e+11,1.606661e+11,2025-11-30,2025-12-31
13,14,PE,53.733012,58.913359,60.454722,20.487823,98.549642,0.950827,0.920993,0.010622,5070.714804,-5070.714804,1.631096e+11,1.613952e+11,2025-11-30,2025-12-31
14,15,SE,50.535149,57.066965,55.941849,15.672804,98.609554,0.949979,0.918272,0.007420,5063.347448,-5063.347448,4.370124e+10,4.337937e+10,2025-11-30,2025-12-31
15,16,AC,49.008999,57.554953,60.028147,10.112701,83.28146,0.950203,0.920736,0.003722,6948.226516,-6948.226516,1.869736e+10,1.862803e+10,2025-11-30,2025-12-31
16,17,AL,48.901999,55.373161,56.458224,10.335703,100.0,0.949201,0.918583,0.003870,4892.365855,-4892.365855,5.646625e+10,5.624855e+10,2025-11-30,2025-12-31
17,18,RN,47.0313,58.127315,53.397363,3.899925,96.925492,0.950466,0.916738,-0.000410,5270.434744,-5270.434744,6.727312e+10,6.730070e+10,2025-11-30,2025-12-31
18,19,AP,46.779232,55.211072,51.245624,16.298880,80.069498,0.949127,0.915440,0.007836,7343.198,-7343.198,1.833766e+10,1.819508e+10,2025-11-30,2025-12-31
19,20,PA,46.248946,48.617052,52.037059,18.103409,90.960076,0.946098,0.915918,0.009037,6003.99555,-6003.99555,1.560704e+11,1.546727e+11,2025-11-30,2025-12-31
20,21,PB,41.031964,46.035666,44.511809,7.649179,96.536437,0.944913,0.911380,0.002084,5318.276452,-5318.276452,7.223354e+10,7.208334e+10,2025-11-30,2025-12-31
21,22,MT,35.800764,48.833619,36.515341,31.017580,0.0,0.946198,0.906558,0.017625,17189.257259,-17189.257259,2.558127e+11,2.513820e+11,2025-11-30,2025-12-31
22,23,RO,34.422408,41.443440,38.358185,9.550292,60.221761,0.942804,0.907669,0.003348,9783.852711,-9783.852711,6.220092e+10,6.199336e+10,2025-11-30,2025-12-31
23,24,GO,29.673033,38.663038,22.967287,18.419610,46.458815,0.941527,0.898389,0.009247,11476.267256,-11476.267256,3.301673e+11,3.271423e+11,2025-11-30,2025-12-31
24,25,MS,25.197357,38.191751,10.662575,13.989337,51.341376,0.941311,0.890969,0.006300,10875.864002,-10875.864002,1.368505e+11,1.359937e+11,2025-11-30,2025-12-31
25,26,TO,18.245897,11.041042,5.456810,28.753327,55.561574,0.928842,0.887830,0.016120,10356.910859,-10356.910859,5.593609e+10,5.504873e+10,2025-11-30,2025-12-31
26,27,MA,10.339968,0.000000,0.000000,3.101165,95.646773,0.923771,0.884540,-0.000941,5427.677409,-5427.677409,1.085140e+11,1.086162e+11,2025-11-30,2025-12-31

In [26]:
# variacao 4: score com dinamismo ajustado ao risco.
# diferenca em relacao ao oficial: o crescimento da carteira (dinamismo)
# so e totalmente recompensado se a inadimplencia do estado for baixa.
# crescimento alto com inadimplencia alta e penalizado.
#
# obs: esta celula recalcula tudo do zero, com periodo_anterior = janeiro
# (igual ao oficial), entao nao depende das celulas anteriores do anexo.

base_estado_data = (
    dt.groupby(["uf", "data_base"], as_index=False)
    .agg({
        "carteira_ativa": "sum",
        "carteira_inadimplencia": "sum",
        "ativo_problematico": "sum",
        "numero_de_operacoes": "sum",
    })
)

base_estado_data = base_estado_data.sort_values(["uf", "data_base"])

periodo_atual = (
    base_estado_data
    .groupby("uf", as_index=False)
    .last()
    .rename(columns={
        "data_base": "data_atual",
        "carteira_ativa": "carteira_ativa_atual",
        "carteira_inadimplencia": "carteira_inadimplencia_atual",
        "ativo_problematico": "ativo_problematico_atual",
        "numero_de_operacoes": "numero_de_operacoes_atual",
    })
)

periodo_anterior = (
    base_estado_data
    .groupby("uf", as_index=False)
    .first()
    .rename(columns={
        "data_base": "data_anterior",
        "carteira_ativa": "carteira_ativa_anterior",
        "carteira_inadimplencia": "carteira_inadimplencia_anterior",
        "ativo_problematico": "ativo_problematico_anterior",
        "numero_de_operacoes": "numero_de_operacoes_anterior",
    })
)

score_estudo_dinamismo_ajustado_risco = periodo_atual.merge(
    periodo_anterior,
    on="uf",
    how="inner"
)

score_estudo_dinamismo_ajustado_risco = score_estudo_dinamismo_ajustado_risco[
    (score_estudo_dinamismo_ajustado_risco["carteira_ativa_atual"] > 0) &
    (score_estudo_dinamismo_ajustado_risco["carteira_ativa_anterior"] > 0) &
    (score_estudo_dinamismo_ajustado_risco["numero_de_operacoes_atual"] > 0)
].copy()

# qualidade: quanto menor a inadimplencia, melhor.
score_estudo_dinamismo_ajustado_risco["taxa_inadimplencia"] = (
    score_estudo_dinamismo_ajustado_risco["carteira_inadimplencia_atual"]
    / score_estudo_dinamismo_ajustado_risco["carteira_ativa_atual"]
)

score_estudo_dinamismo_ajustado_risco["qualidade"] = (
    1 - score_estudo_dinamismo_ajustado_risco["taxa_inadimplencia"]
)

# solidez: quanto menor o ativo problematico, melhor.
score_estudo_dinamismo_ajustado_risco["taxa_ativo_problematico"] = (
    score_estudo_dinamismo_ajustado_risco["ativo_problematico_atual"]
    / score_estudo_dinamismo_ajustado_risco["carteira_ativa_atual"]
)

score_estudo_dinamismo_ajustado_risco["solidez"] = (
    1 - score_estudo_dinamismo_ajustado_risco["taxa_ativo_problematico"]
)

# crescimento bruto da carteira (igual ao dinamismo oficial).
score_estudo_dinamismo_ajustado_risco["crescimento_carteira"] = (
    (
        score_estudo_dinamismo_ajustado_risco["carteira_ativa_atual"]
        - score_estudo_dinamismo_ajustado_risco["carteira_ativa_anterior"]
    )
    / score_estudo_dinamismo_ajustado_risco["carteira_ativa_anterior"]
)

# dinamismo ajustado ao risco: o crescimento so conta "cheio" se a
# inadimplencia for proxima de zero.
score_estudo_dinamismo_ajustado_risco["dinamismo"] = (
    score_estudo_dinamismo_ajustado_risco["crescimento_carteira"]
    * (1 - score_estudo_dinamismo_ajustado_risco["taxa_inadimplencia"])
)

# eficiencia: ticket medio (igual ao oficial).
score_estudo_dinamismo_ajustado_risco["eficiencia"] = (
    score_estudo_dinamismo_ajustado_risco["carteira_ativa_atual"]
    / score_estudo_dinamismo_ajustado_risco["numero_de_operacoes_atual"]
)

score_estudo_dinamismo_ajustado_risco["qualidade_norm"] = normalizar_componente(score_estudo_dinamismo_ajustado_risco["qualidade"])
score_estudo_dinamismo_ajustado_risco["solidez_norm"] = normalizar_componente(score_estudo_dinamismo_ajustado_risco["solidez"])
score_estudo_dinamismo_ajustado_risco["dinamismo_norm"] = normalizar_componente(score_estudo_dinamismo_ajustado_risco["dinamismo"])
score_estudo_dinamismo_ajustado_risco["eficiencia_norm"] = normalizar_componente(score_estudo_dinamismo_ajustado_risco["eficiencia"])

score_estudo_dinamismo_ajustado_risco["score_final"] = (
    score_estudo_dinamismo_ajustado_risco["qualidade_norm"] * 0.35
    + score_estudo_dinamismo_ajustado_risco["solidez_norm"] * 0.30
    + score_estudo_dinamismo_ajustado_risco["dinamismo_norm"] * 0.25
    + score_estudo_dinamismo_ajustado_risco["eficiencia_norm"] * 0.10
)

ranking_estudo_dinamismo_ajustado_risco = (
    score_estudo_dinamismo_ajustado_risco
    .sort_values("score_final", ascending=False)
    .reset_index(drop=True)
)

ranking_estudo_dinamismo_ajustado_risco["posicao"] = ranking_estudo_dinamismo_ajustado_risco.index + 1

ranking_estudo_dinamismo_ajustado_risco = ranking_estudo_dinamismo_ajustado_risco[[
    "posicao",
    "uf",
    "score_final",
    "qualidade_norm",
    "solidez_norm",
    "dinamismo_norm",
    "eficiencia_norm",
    "qualidade",
    "solidez",
    "dinamismo",
    "crescimento_carteira",
    "taxa_inadimplencia",
    "taxa_ativo_problematico",
    "eficiencia",
    "carteira_ativa_atual",
    "carteira_ativa_anterior",
    "data_anterior",
    "data_atual",
]].copy()

display(ranking_estudo_dinamismo_ajustado_risco)

,posicao,uf,score_final,qualidade_norm,solidez_norm,dinamismo_norm,eficiencia_norm,qualidade,solidez,dinamismo,crescimento_carteira,taxa_inadimplencia,taxa_ativo_problematico,eficiencia,carteira_ativa_atual,carteira_ativa_anterior,data_anterior,data_atual
0,1,SP,86.006653,95.489836,79.760510,100.000000,36.570573,0.967625,0.932634,0.168129,0.173754,0.032375,0.067366,9389.409498,2.192362e+12,1.867821e+12,2025-01-31,2025-12-31
1,2,SC,78.72654,96.468321,97.169260,42.774544,51.182136,0.968074,0.943132,0.093954,0.097053,0.031926,0.056868,11186.177521,3.919637e+11,3.572879e+11,2025-01-31,2025-12-31
2,3,DF,74.050421,100.000000,100.000000,14.671775,53.824769,0.969696,0.944838,0.057528,0.059326,0.030304,0.055162,11511.139188,1.694249e+11,1.599365e+11,2025-01-31,2025-12-31
3,4,ES,69.130269,86.560590,68.393636,63.173517,25.22593,0.963524,0.925780,0.120395,0.124953,0.036476,0.074220,7994.371014,1.235319e+11,1.098108e+11,2025-01-31,2025-12-31
4,5,PR,66.967082,83.377976,78.285319,39.781517,43.538157,0.962062,0.931745,0.090075,0.093627,0.037938,0.068255,10246.205797,5.373201e+11,4.913194e+11,2025-01-31,2025-12-31
5,6,RS,65.322325,77.898343,68.808706,55.392415,35.671895,0.959546,0.926031,0.110309,0.114960,0.040454,0.073969,9278.90007,5.165961e+11,4.633315e+11,2025-01-31,2025-12-31
6,7,AM,65.307651,57.960906,67.330719,95.296460,9.980034,0.950390,0.925139,0.162032,0.170490,0.049610,0.074861,6119.599842,7.602753e+10,6.495358e+10,2025-01-31,2025-12-31
7,8,PI,60.653923,71.389396,74.273783,49.486607,10.138483,0.956557,0.929326,0.102654,0.107316,0.043443,0.070674,6139.084064,6.332587e+10,5.718859e+10,2025-01-31,2025-12-31
8,9,MG,59.258472,77.327858,73.939293,30.757235,23.22625,0.959284,0.929124,0.078378,0.081704,0.040716,0.070876,7748.472564,6.325402e+11,5.847626e+11,2025-01-31,2025-12-31
9,10,CE,59.048041,63.638965,64.283618,68.345603,4.029164,0.952997,0.923302,0.127099,0.133368,0.047003,0.076698,5387.827811,1.614964e+11,1.424925e+11,2025-01-31,2025-12-31
10,11,AP,57.724439,55.211072,51.245624,84.135306,19.930502,0.949127,0.915440,0.147565,0.155475,0.050873,0.084560,7343.198,1.833766e+10,1.587024e+10,2025-01-31,2025-12-31
11,12,RR,57.330771,47.343856,52.737971,98.675469,2.701631,0.945514,0.916340,0.166412,0.176002,0.054486,0.083660,5224.582441,1.539286e+10,1.308915e+10,2025-01-31,2025-12-31
12,13,PE,52.634909,58.913359,60.454722,54.935122,1.450358,0.950827,0.920993,0.109717,0.115391,0.049173,0.079007,5070.714804,1.631096e+11,1.462354e+11,2025-01-31,2025-12-31
13,14,SE,50.878828,57.066965,55.941849,55.935166,1.390446,0.949979,0.918272,0.111013,0.116858,0.050021,0.081728,5063.347448,4.370124e+10,3.912873e+10,2025-01-31,2025-12-31
14,15,AC,49.87528,57.554953,60.028147,40.202995,16.71854,0.950203,0.920736,0.090621,0.095370,0.049797,0.079264,6948.226516,1.869736e+10,1.706945e+10,2025-01-31,2025-12-31
15,16,AL,49.635003,55.373161,56.458224,53.267719,0.0,0.949201,0.918583,0.107555,0.113311,0.050799,0.081417,4892.365855,5.646625e+10,5.071919e+10,2025-01-31,2025-12-31
16,17,BA,48.38305,59.780107,57.684409,38.978959,4.099506,0.951225,0.919323,0.089035,0.093600,0.048775,0.080677,5396.477637,2.718438e+11,2.485770e+11,2025-01-31,2025-12-31
17,18,PA,48.137406,48.617052,52.037059,58.425311,9.039924,0.946098,0.915918,0.114240,0.120749,0.053902,0.084082,6003.99555,1.560704e+11,1.392554e+11,2025-01-31,2025-12-31
18,19,RN,47.616848,58.127315,53.397363,43.782511,3.074508,0.950466,0.916738,0.095261,0.100225,0.049534,0.083262,5270.434744,6.727312e+10,6.114486e+10,2025-01-31,2025-12-31
19,20,RJ,47.036582,79.205994,57.897972,0.000000,19.450924,0.960146,0.919452,0.038511,0.040109,0.039854,0.080548,7284.224887,5.340927e+11,5.134968e+11,2025-01-31,2025-12-31
20,21,PB,44.15956,46.035666,44.511809,57.388713,3.463563,0.944913,0.911380,0.112897,0.119479,0.055087,0.088620,5318.276452,7.223354e+10,6.452427e+10,2025-01-31,2025-12-31
21,22,MT,42.676556,48.833619,36.515341,18.520748,100.0,0.946198,0.906558,0.062517,0.066072,0.053802,0.093442,17189.257259,2.558127e+11,2.399582e+11,2025-01-31,2025-12-31
22,23,GO,35.285298,38.663038,22.967287,38.035719,53.541185,0.941527,0.898389,0.087812,0.093265,0.058473,0.101611,11476.267256,3.301673e+11,3.020011e+11,2025-01-31,2025-12-31
23,24,RO,34.984811,41.443440,38.358185,19.977310,39.778239,0.942804,0.907669,0.064405,0.068312,0.057196,0.092331,9783.852711,6.220092e+10,5.822355e+10,2025-01-31,2025-12-31
24,25,TO,34.755368,11.041042,5.456810,99.240469,44.438426,0.928842,0.887830,0.167144,0.179949,0.071158,0.112170,10356.910859,5.593609e+10,4.740551e+10,2025-01-31,2025-12-31
25,26,MS,26.164355,38.191751,10.662575,18.930430,48.658624,0.941311,0.890969,0.063048,0.066979,0.058689,0.109031,10875.864002,1.368505e+11,1.282598e+11,2025-01-31,2025-12-31
26,27,MA,13.600967,0.000000,0.000000,52.662577,4.353227,0.923771,0.884540,0.106771,0.115582,0.076229,0.115460,5427.677409,1.085140e+11,9.727125e+10,2025-01-31,2025-12-31

In [27]:
# exporta todas as variacoes de score estudadas (nao usadas no projeto
# final) para analise comparativa externa.

from google.colab import files

ranking_estudo_dinamismo_mensal.to_excel("estudo_dinamismo_mensal.xlsx", index=False)
ranking_estudo_oportunidade_populacional.to_excel("estudo_oportunidade_populacional.xlsx", index=False)
ranking_estudo_eficiencia_invertida.to_excel("estudo_eficiencia_invertida.xlsx", index=False)
ranking_estudo_dinamismo_ajustado_risco.to_excel("estudo_dinamismo_ajustado_risco.xlsx", index=False)

arquivos_estudo = [
    "estudo_dinamismo_mensal.xlsx",
    "estudo_oportunidade_populacional.xlsx",
    "estudo_eficiencia_invertida.xlsx",
    "estudo_dinamismo_ajustado_risco.xlsx",
]

for arquivo in arquivos_estudo:
    files.download(arquivo)